# Generated by Django 3.1.4 on 2020-12-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201220_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin_url',
            new_name='linkedin_Url',
        ),
    ]
